apiVersion: apps/v1
kind: Deployment
metadata:
  name: atolye15-deployment
  labels:
    app: atolye15
spec:
  selector:
    matchLabels:
      app: atolye15
  template:
    metadata:
      labels:
        app: atolye15
    spec:
      containers:
        - name: atolye15
          image: gcr.io/centering-land-385713/atolye15:master
          ports:
            - containerPort: 3000
